import AdminShell from '@/components/AdminShell'
import { formatAdminDate, getAdminData } from '@/lib/server/admin-data'

export const dynamic = 'force-dynamic'

export default async function AdminTasksPage() {
  const { taskRows } = await getAdminData()

  return (
    <AdminShell active="tasks">
      <section className="admin-content">
        <div className="admin-section-head">
          <span>Tasks</span>
          <h2>Task Activity</h2>
          <p>Planner tasks generated by users, with completion progress from subtasks.</p>
        </div>

        <section className="admin-table-card admin-task-table">
          <div className="admin-table-head">
            <span>Task</span>
            <span>User</span>
            <span>Progress</span>
            <span>Status</span>
            <span>Created</span>
          </div>
          {taskRows.map(task => (
            <div className="admin-table-row" key={task.id}>
              <strong>{task.inputText}</strong>
              <span>{task.userEmail}</span>
              <span>{task.progress}</span>
              <em className={task.status === 'Completed' ? 'active' : 'trial'}>{task.status}</em>
              <span>{formatAdminDate(task.createdAt)}</span>
            </div>
          ))}
          {!taskRows.length && <p className="admin-empty">No tasks yet.</p>}
        </section>
      </section>
    </AdminShell>
  )
}
